### ISSUE TITLE
Reformatting AreaCharts into a more Modularized way 

### ISSUE THREAD

**Issue by jarhun88** [Sustaingineeringubc/Horus-Monitoring#22]
Right now, the single area chart we have is just pasted into the dashboard.jsx. Later on, I assume we will be creating many more charts onto the dashboard page, and so it makes sense to create a separate charts component implementation. 

This will (hopefully) make it easier for us to reuse the same chart implementation to create the unique Voltage, Current, Power, etc, charts down the line.

**Comment by jluisfgarza** [comment]
I resolved all the issues with the issue-29 pr #34
