### ISSUE TITLE
Forgot Password UI

### ISSUE THREAD

**Issue by aviquez96** [Sustaingineeringubc/Horus-Monitoring#39]
Tasks:

a) Create a "forgot password" link to a new page called "forgotPassword.jsx" from "signIn.jsx"

b) In forgotPassword.jsx
   1) Make a text field that asks for the user's email
   2) Once asked, render 2 text fields, one asking for the email, and another for the key they got in 
   their email.
   3) If successful, redirect to "newPassword.jsx"

c) In newPassword.jsx
   1) Add two text fields, asking for password, and new password
   
- Handle errors appropriately (subject to conversation with peers if needed)
- Make nice UI with appropriate format/questions (see other Forgot Password pages for reference)

**Comment by febg** [comment]
@aviquez96 What about a page where the user can enter and save the new password after its being verified.

Also you can use this space to link specific functionality to API tools. For example:
To your step 1) Make a text field that asks for the user's email.
     After doing this, the front-end team can use the `email-exists` API to verify that the email address exists, if it does a recovery email will be sent to that email

The list of apis is located here

https://docs.google.com/document/d/1001j5SySA-O8BRARdyrh8OxJlnEBlgcizdcXGqkulI8/edit?usp=sharing

@israeltq maybe we can add some description of basic functionality of each function. Like explaining it will verify the email and then send a recovery email as well as explaining what would happen if the email doesnt exists. Also I think we should rename this function as it is not very intuitive that it will send a recovery email after checking if the email exists.

**Comment by febg** [comment]
Adding to my previous comment, in order to save the new password the fornt-end team can use the  `reset-password` API :)

**Comment by aviquez96** [comment]
I updated the original comment adding the extra page you suggested - I think that's a good addition. Perhaps when @israeltq or @omaragha98 add the description of the API's, I can re-edit the original comment to make use of the API's, sounds good? 

Once that update is done, I will check again.

**Comment by israeltq** [comment]
So yeah basically the email-exists function receives an email entered by the user. If the email exists, then the function will send a random code to that email. If it does not, then it just returns an error message. I am not sure if this is what you want

**Comment by aviquez96** [comment]
Yeah, that's good! I guess what I meant, perhaps what @febg also meant, was commenting the API's so that you say like "retrieves email" or something. What do you think?
